### ISSUE TITLE
can't run autoconf --force

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [chaos/genders#32] opened 2019-10-30 02:38 UTC
In version 1-26-1
```
***** autoconf *****
***** PWD: /var/tmp/portage/sys-cluster/genders-1.26.1/work/genders-genders-1-26-1
***** autoconf --force

configure.ac:11: error: possibly undefined macro: AC_META
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:89: error: possibly undefined macro: AC_DEBUG
configure.ac:155: error: possibly undefined macro: AC_GENDERS_FILE
configure.ac:160: error: possibly undefined macro: AC_EXTENSION_DESTDIR
configure.ac:165: error: possibly undefined macro: AC_PERL_EXTENSIONS
configure.ac:177: error: possibly undefined macro: AC_PERL_SITE_ARCH
configure.ac:178: error: possibly undefined macro: AC_PERL_VENDOR_ARCH
configure.ac:194: error: possibly undefined macro: AC_PYTHON_EXTENSIONS
configure.ac:200: error: possibly undefined macro: AC_CPLUSPLUS_EXTENSIONS
configure.ac:206: error: possibly undefined macro: AC_JAVA_EXTENSIONS

```

**Comment by chu11** [comment] 2019-10-30 04:53
are you running `autogen.sh`? or doing this by hand?

**Comment by Alessandro-Barbieri** [comment] 2019-10-30 10:37
I'm doing it manually

**Comment by Alessandro-Barbieri** [comment] 2019-10-30 15:40
I have run (not actually me but the gentoo build system)
```
libtoolize --install --copy --force --automake
aclocal
autoconf --force
```

Running `autogen.sh` will work but with warnings about the same macros

**Comment by chu11** [comment] 2019-10-31 15:29
I believe the issue is aclocal needs the `-I config` line, otherwise it can't find certain macros.

I assume things are working now, so closing this issue.

**Closed by chu11** 2019-10-31 15:29 UTC
